version: '3'
services:
  go_app:
    container_name: goql_ctn
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - go_dev
  
  psql_db:
    container_name: psql_db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - go_dev
  
networks:
  go_dev:
    driver: bridge

volumes:
  postgres-db:
    driver: local