package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/AhmedEnnaime/GoQl/db"
	"github.com/AhmedEnnaime/GoQl/graph/model"
)

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, input model.QuestionInput) (*model.Question, error) {
	db := db.Model

	question := &model.Question{
		// ID:           fmt.Sprintf("T%d", rand.Int()),
		QuestionText: input.QuestionText,
		PubDate:      input.PubDate,
	}

	if err := db.Create(&question).Error; err != nil {
		return nil, err
	}

	r.questions = append(r.questions, question)
	return question, nil
}

// CreateChoice is the resolver for the createChoice field.
func (r *mutationResolver) CreateChoice(ctx context.Context, input *model.ChoiceInput) (*model.Choice, error) {
	panic(fmt.Errorf("not implemented: CreateChoice - createChoice"))
}

// Questions is the resolver for the questions field.
func (r *queryResolver) Questions(ctx context.Context) ([]*model.Question, error) {
	DEFAULT_LIMIT := 20
	question := []*model.Question{}

	db := db.Model

	if limit := ctx.Value("limit"); limit != nil {
		limit := int(limit.(int))
		DEFAULT_LIMIT = limit
	}

	if id := ctx.Value("id"); id != nil {
		id := int(id.(int))
		if err := db.First(&question, "id=?", id).Error; err != nil {
			return nil, err
		}
		return question, nil
	}

	if err := db.Limit(DEFAULT_LIMIT).Find(&question).Error; err != nil {
		return nil, err
	}

	return question, nil
}

// Choices is the resolver for the choices field.
func (r *queryResolver) Choices(ctx context.Context) ([]*model.Choice, error) {
	panic(fmt.Errorf("not implemented: Choices - choices"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
